=== pxslip/savoy-smash/schemas/cocktail.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://savoy-smash.pxslip.com/schemas/cocktail.schema.json",
	"title": "Cocktail",
	"description": "The ingredients, and directions required to make a cocktail",
	"type": "object",
	"properties": {
		"source": {
			"type": "string",
			"description": "Where did this cocktail originate from? Savoy Cocktail book, Trader Vic's, etc."
		},
		"version": {
			"type": "string",
			"description": "Which version of the cocktail is this? e.g. Original, mine, or a named creator"
		},
		"directions": {
			"type": "string",
			"description": "Instructions for making this version of the cocktail"
		},
		"ingredients": {
			"$comment": "Allow for a top level Ingredient object, or a nested array of ingredients for ingredients that offer options",
			"description": "A list of ingredients and amounts used in the cocktail",
			"type": "array",
			"items": [
				{
					"$ref": "#/definitions/Ingredient"
				},
				{
					"type": "array",
					"items": {
						"$ref": "#/definitions/Ingredient"
					}
				}
			]
		}
	},
	"definitions": {
		"Ingredient": {
			"description": "A reference to an ingredient that can be used in a cocktail",
			"type": "object",
			"properties": {
				"ingredient": {
					"type": "string",
					"$comment": "A path-style reference to an Ingredient"
				},
				"amount": {
					"type": "string"
				},
				"measurement": {
					"type": "string"
				}
			}
		}
	}
}

=== pxslip/savoy-smash/content/cocktails/appetiser/_versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/gin",
			"amount": 0.5,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/dubonnet",
			"amount": 0.5,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/orange-juice",
			"amount": 1,
			"unit": "/measurements/ounce"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/trilby-no-2/_versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/absinthe",
			"amount": 2,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/orange-bitters",
			"amount": 2,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/parfait-amour",
			"amount": 0.3,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/whisky-scotch",
			"amount": 0.3,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/italian-vermouth",
			"amount": 0.3,
			"unit": "/measurements/none"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/fog-cutter/versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/bartenders-guide-trader-vic",
	"directions": "Shake all but sherry with cracked ice; pour into 14-oz. glass and add more cracked ice. Add sherry wine float; serve with straws.",
	"ingredients": [
		{
			"ingredient": "/ingredients/rum-puerto-rican",
			"amount": 2,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/brandy",
			"amount": 1,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/gin",
			"amount": 0.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/orange-juice",
			"amount": 1,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/lemon-juice",
			"amount": 2,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/orgeat",
			"amount": 0.5,
			"unit": "/measurements/ounce"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/maidens-prayer-no-2/_versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/kina-lillet",
			"amount": 0.3,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/dry-gin",
			"amount": 0.3,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/calvados",
			"amount": 0.16,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/pricota",
			"amount": 0.16,
			"unit": "/measurements/none"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/alfonso-special/versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/angostura-bitters",
			"amount": 1,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/italian-vermouth",
			"amount": 4,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/dry-gin",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/french-vermouth",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/grand-marnier",
			"amount": 0.5,
			"unit": "/measurements/none"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/star-no-1/_versions/original.json
{
	"version": "original",
	"$schema": "../../../../schemas/cocktail.schema.json",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass",
	"ingredients": [
		{
			"ingredient": "/ingredients/grapefruit-juice",
			"amount": 1,
			"unit": "/measurements/teaspoon"
		},
		{
			"ingredient": "/ingredients/italian-vermouth",
			"amount": 1,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/french-vermouth",
			"amount": 1,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/apple-brandy",
			"amount": 0.5,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/dry-gin",
			"amount": 0.5,
			"unit": "/measurements/none"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/damn-the-weather/_versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/curacao",
			"amount": 3,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/orange-juice",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/italian-vermouth",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/dry-gin",
			"amount": 0.5,
			"unit": "/measurements/none"
		}
	]
}
