=== pxslip/savoy-smash/schemas/cocktail.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://savoy-smash.pxslip.com/schemas/cocktail.schema.json",
	"title": "Cocktail",
	"description": "The ingredients, and directions required to make a cocktail",
	"type": "object",
	"properties": {
		"source": {
			"type": "string",
			"description": "Where did this cocktail originate from? Savoy Cocktail book, Trader Vic's, etc."
		},
		"version": {
			"type": "string",
			"description": "Which version of the cocktail is this? e.g. Original, mine, or a named creator"
		},
		"directions": {
			"type": "string",
			"description": "Instructions for making this version of the cocktail"
		},
		"ingredients": {
			"$comment": "Allow for a top level Ingredient object, or a nested array of ingredients for ingredients that offer options",
			"description": "A list of ingredients and amounts used in the cocktail",
			"type": "array",
			"items": [
				{
					"$ref": "#/definitions/Ingredient"
				},
				{
					"type": "array",
					"items": {
						"$ref": "#/definitions/Ingredient"
					}
				}
			]
		}
	},
	"definitions": {
		"Ingredient": {
			"description": "A reference to an ingredient that can be used in a cocktail",
			"type": "object",
			"properties": {
				"ingredient": {
					"type": "string",
					"$comment": "A path-style reference to an Ingredient"
				},
				"amount": {
					"type": "string"
				},
				"measurement": {
					"type": "string"
				}
			}
		}
	}
}

=== pxslip/savoy-smash/content/cocktails/hootsmon/versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Stir well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/kina-lillet",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/italian-vermouth",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/whisky-scotch",
			"amount": 0.5,
			"unit": "/measurements/none"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/modern-no-1/_versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/orange-bitters",
			"amount": 1,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/rum-jamaica",
			"amount": 2,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/absinthe",
			"amount": 1,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/lemon-juice",
			"amount": 2,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/whisky-scotch",
			"amount": 1,
			"unit": "/measurements/glass"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/jungle-bird/_versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/new-american-bartenders-guide",
	"directions": "Shake until well chilled, and strain into a double old-fashioned glass over a large ice cube. Garnish with the pineapple wedge or leaf (or both).",
	"ingredients": [
		{
			"ingredient": "/ingredients/rum-blackstrap",
			"amount": 1.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/pineapple-juice",
			"amount": 1.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/campari",
			"amount": 0.75,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/lime-juice",
			"amount": 0.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/symple-syrup",
			"amount": 0.5,
			"unit": "/measurements/ounce"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/boomerang/versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/lemon-juice",
			"amount": 1,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/angostura-bitters",
			"amount": 1,
			"unit": "/measurements/dash"
		},
		{
			"ingredient": "/ingredients/french-vermouth",
			"amount": 0.3,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/whisky-canadian-club",
			"amount": 0.3,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/swedish-punch",
			"amount": 0.3,
			"unit": "/measurements/none"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/italian-bird/versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Add all ingredients to a mixing glass with ice. Stir until well chilled. Strain into a rocks glass with ice. Garnish with pineapple sage.",
	"ingredients": [
		{
			"ingredient": "/ingredients/rum-aged",
			"amount": 1.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/campari",
			"amount": 0.75,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/sherry-fino",
			"amount": 0.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/honey-syrup",
			"amount": 0.5,
			"unit": "/measurements/ounce"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/painkiller/_versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/pussers-painkiller",
	"directions": "- Add liquid ingredients to a cocktail shaker and shake vigorously.\n- Pour into a big glass or goblet filled with ice. Grate fresh nutmeg on top.\n- Garnish with an orange slice and cherry.",
	"ingredients": [
		{
			"ingredient": "/ingredients/rum",
			"amount": 2,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/pineapple-juice",
			"amount": 4,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/orange-juice",
			"amount": 1,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/cream-of-coconut",
			"amount": 1,
			"unit": "/measurements/ounce"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/hoop-la/versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "Shake well and strain into a cocktail glass.",
	"ingredients": [
		{
			"ingredient": "/ingredients/lemon-juice",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/kina-lillet",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/cointreau",
			"amount": 0.25,
			"unit": "/measurements/none"
		},
		{
			"ingredient": "/ingredients/brandy",
			"amount": 0.25,
			"unit": "/measurements/none"
		}
	]
}

=== pxslip/savoy-smash/content/cocktails/singapore-sling/_versions/original.json
{
	"$schema": "../../../../schemas/cocktail.schema.json",
	"version": "original",
	"source": "/sources/savoy-cocktail-book-harry-craddock",
	"directions": "- Shake all ingredients with ice\n- Strain into an ice-filled glass",
	"ingredients": [
		{
			"ingredient": "/ingredients/dry-gin",
			"amount": 1.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/cherry-brandy",
			"amount": 0.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/benedictine",
			"amount": 0.25,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/cointreau",
			"amount": 0.25,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/pineapple-juice",
			"amount": 1.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/lime-juice",
			"amount": 0.5,
			"unit": "/measurements/ounce"
		},
		{
			"ingredient": "/ingredients/grenadine",
			"amount": 1,
			"unit": "/measurements/dash"
		}
	]
}
